# Generated by Django 4.1.1 on 2022-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('paper', models.IntegerField()),
                ('copies', models.IntegerField()),
                ('sides', models.IntegerField()),
                ('oversized', models.BooleanField()),
                ('color', models.BooleanField()),
                ('mark_up', models.IntegerField()),
                ('finishing', models.IntegerField()),
                ('package', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
