# Generated by Django 4.1.1 on 2022-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_name',
            field=models.CharField(max_length=200),
        ),
    ]
