# Generated by Django 4.1.1 on 2022-10-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_job_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finishing',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='mark_up',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cost',
            field=models.FloatField(),
        ),
    ]
