# Generated by Django 4.1.1 on 2022-10-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finishing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='mark_up',
            field=models.FloatField(default=6),
        ),
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.FloatField(default=0),
        ),
    ]
